### ISSUE TITLE
不支持多音字？

### ISSUE THREAD

**Issue by hanzichi** [liuxianan/pinyinjs#1]
喝彩 => hē cǎi

**Comment by hustcc** [comment]
重庆 -> zhòng qìng

**Comment by Pszz** [comment]
你的 -->  nǐ dí

**Comment by hustcc** [comment]
汉字转拼音：[http://www.atool.org/hanzi2pinyin.php](http://www.atool.org/hanzi2pinyin.php)

**Comment by liuxianan** [comment]
已更新对多音字的支持，请查看：
http://demo.liuxianan.com/pinyinjs/polyphone.html
http://blog.liuxianan.com/pinyinjs.html#guan-yu-duo-yin-zi

鉴于很多人都比较关心多音字的问题，所以单独拿出一个小章节来介绍多音字的相关问题。

准确识别各种复杂语句中混杂的多音字其实并没有那么容易，有两个关键的地方，一个是多音字词库的丰富程度，一个是能否正确的给语句进行分词。而词库和分词的实现都需要一个非常丰富的`词典`文件，现代汉语词语有多少个，估计没有人算得清，再加上每天新出现的人名、网络词语、科技词语等等。一个普通的词库文件至少也有几百kb，所以不太适合web环境下去实现，一般最好放在服务器端做成一个接口。

鉴于很多人都希望有多音字识别的功能，所以我简单实现了一个版本。词库文件是从[这里](https://github.com/hotoo/pinyin/tree/master/data/phrases-dict.js)找到的，并根据实际情况将文件从`1.8M`压缩到了`912kb`，分词暂时只是自己非常简单的实现(也可以说压根就没有分词)，如果是服务器端推荐几个不错的中文分词工具：Python版的[Jieba](https://github.com/fxsjy/jieba)和[NodeJieba](https://github.com/yanyiwu/nodejieba)，性能非常好，其它语言版的参考上面项目的README。

关于分词，摘抄一段网络解释：

> 词是最小的能够独立活动的有意义的语言成分，英文单词之间是以空格作为自然分界符的，而汉语是以字为基本的书写单位，词语之间没有明显的区分标记，因此，要对中文信息进行处理，正确的分词就显得尤为关键。

比如`看中国`这一个词，单独的`看中`读`kàn zhòng`，`中国`读`zhōng guó`，连在一起却读作`kàn zhōng guó`。

我这个实现非常得简单，效果一般，性能也一般，需要下载将近1M的词库文件，所以不适合web环境，演示地址：

http://demo.liuxianan.com/pinyinjs/polyphone.html
